export const Data = [
  {
    name: "magnetic_series",
    src: "/images/Products/Product1.webp",
    title: "Magnetic Series",
    text: "Innovative magnetic lighting for flexible positioning.",
  },
  {
    name: "cob_light",
    src: "/images/Products/Product2.webp",
    title: "COB Light",
    text: "Compact, high-brightness COB lighting solutions.",
  },
  {
    name: "track_zoom",
    src: "/images/Products/Product3.webp",
    title: "Track And Zoom",
    text: "Adjustable lighting system for dynamic spaces.",
  },
  {
    name: "panel_surface",
    src: "/images/Products/Product4.webp",
    title: "Panel and Surface",
    text: "Sleek and efficient lighting for walls and ceilings.",
  },
  {
    name: "flood_light",
    src: "/images/Products/Product5.webp",
    title: "Flood Light",
    text: "Powerful lighting for outdoor and large areas.",
  },
  {
    name: "highbay",
    src: "/images/Products/Product6.webp",
    title: "Highbay",
    text: "Energy-efficient lighting for high ceilings.",
  },
  {
    name: "street_light",
    src: "/images/Products/Product7.webp",
    title: "Street Light",
    text: "Durable and bright lighting for roads and pathways.",
  },
  {
    name: "aluminium_batten",
    src: "/images/Products/Product8.webp",
    title: "Aluminium Batten",
    text: "Sleek and sturdy batten lights for various spaces.",
  },
  {
    name: "strip_light",
    src: "/images/Products/Product9.webp",
    title: "Strip Light",
    text: "Versatile lighting for creative and functional setups.",
  },
  {
    name: "smps",
    src: "/images/Products/Product10.webp",
    title: "SMPS",
    text: "Reliable power supply for LED lighting systems.",
  },
  {
    name: "rope_light",
    src: "/images/Products/Product11.webp",
    title: "Rope Light",
    text: "Flexible and decorative lighting for ambiance.",
  },
  // {
  //   name: "profile_light",
  //   src: "/images/Products/Product1.webp",
  //   title: "Profile",
  //   text: "Sleek aluminum profile lighting for modern spaces.",
  // },
  {
    name: "custom_ceiling_fan",
    src: "/images/Fans/Fans5.webp",
    title: "Customized Ceiling Fan",
  },
  // {
  //   name: "custom_hvls_fan",
  //   src: "/images/Products/Product1.webp",
  //   title: "Customized HVLS Fan",
  //   text: "High-volume, low-speed fans tailored for large spaces.",
  // },
];
